# Generated by Django 6.0.2 on 2026-02-20 02:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('household_name', models.CharField(max_length=255)),
                ('join_code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Join code must be 5 alphanumeric characters.', regex='^[A-Za-z0-9]{5}$')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='api.household')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('all_day', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('repeat', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notification_value', models.IntegerField(blank=True, null=True)),
                ('notification_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True)),
                ('event_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='api.household')),
            ],
        ),
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('all_day', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('repeat', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('is_rotating', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notification_value', models.IntegerField(blank=True, null=True)),
                ('notification_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('assigned_roommate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chores', to=settings.AUTH_USER_MODEL)),
                ('next_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_rotations', to=settings.AUTH_USER_MODEL)),
                ('roommates_involved', models.ManyToManyField(blank=True, related_name='chores_involved', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='api.household')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_purchased_date', models.DateField(blank=True, null=True)),
                ('restock_needed', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.household')),
                ('last_purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_purchased', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.IntegerField(blank=True, null=True)),
                ('clean_up_your_space', models.BooleanField(default=False)),
                ('cook', models.BooleanField(default=False)),
                ('sharing_items', models.BooleanField(default=True)),
                ('pets', models.BooleanField(default=False)),
                ('guests', models.BooleanField(default=True)),
                ('personality_type', models.CharField(blank=True, max_length=50)),
                ('sleep_schedule', models.CharField(blank=True, max_length=50)),
                ('smoking', models.BooleanField(default=False)),
                ('drinking_alcohol', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='living_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_push_notifications', models.BooleanField(default=True)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('calendar_event_notification_on', models.BooleanField(default=True)),
                ('calendar_event_notification_value', models.IntegerField(blank=True, null=True)),
                ('calendar_event_notification_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True)),
                ('roommate_event_approval_needed_notification_on', models.BooleanField(default=True)),
                ('chore_due_notification_on', models.BooleanField(default=True)),
                ('chore_due_notification_value', models.IntegerField(blank=True, null=True)),
                ('chore_due_notification_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True)),
                ('new_chore_notification_on', models.BooleanField(default=True)),
                ('item_restock_notification_on', models.BooleanField(default=True)),
                ('new_roommate_joined_notification_on', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.calendarevents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
