# Generated by Django 6.0.2 on 2026-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chore_choreassignment_delete_chores'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='pass_to_next_unit',
            field=models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='pass_to_next_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
