# Generated by Django 6.0.2 on 2026-03-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chore_pass_to_next_unit_chore_pass_to_next_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='location',
            field=models.CharField(blank=True, choices=[('living room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('other', 'OTHER')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.CharField(blank=True, choices=[('living room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('other', 'OTHER')], max_length=20, null=True),
        ),
    ]
