# Generated by Django 6.0.2 on 2026-03-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_chore_location_alter_items_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='pass_to_next_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10, null=True),
        ),
    ]
