# Generated by Django 6.0.2 on 2026-03-12 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chore_pass_to_next_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreassignment',
            name='next_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
