# Generated by Django 6.0.2 on 2026-03-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_choreassignment_next_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='pass_to_next_unit',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=10, null=True),
        ),
    ]
