# Generated by Django 6.0.2 on 2026-03-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chore_pass_to_next_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='repeat',
        ),
        migrations.AddField(
            model_name='chore',
            name='repeat_unit',
            field=models.CharField(choices=[('none', 'None'), ('days', 'Days'), ('week', 'Weeks'), ('months', 'Months')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='chore',
            name='repeat_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('days', 'Days'), ('week', 'Weeks'), ('months', 'Months')], default='none', max_length=20),
        ),
    ]
