# Generated by Django 6.0.2 on 2026-03-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chore_pass_to_next_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
