# Generated by Django 6.0.2 on 2026-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_chore_repeat_chore_repeat_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreassignment',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
