# Generated by Django 6.0.2 on 2026-03-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_choreassignment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='location',
            field=models.CharField(blank=True, choices=[('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='location',
            field=models.CharField(blank=True, choices=[('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
