# Generated by Django 6.0.2 on 2026-03-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_chore_location_alter_items_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='repeat',
            field=models.CharField(choices=[('none', 'None'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='chore',
            name='repeat_unit',
            field=models.CharField(choices=[('none', 'None'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='none', max_length=20),
        ),
    ]
