# Generated by Django 6.0.2 on 2026-03-31 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_display_color'),
        ('api', '0011_alter_calendarevents_repeat_alter_chore_repeat_unit'),
    ]

    operations = [
    ]
